// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
/*
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  homebar: [
    {
      type: 'category',
      label: 'Home',
      items: ['home'],
    },
  ],
  overviewbar: [
    {
      type: 'category',
      label: 'Overview',
      items: ['overview'],
    },
  ],
  gettingStartedbar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['getting_started'],
    },
  ],
  usingPromptsbar: [
    {
      type: 'category',
      label: 'Using Prompts',
      items: ['using_prompts'],
    },
  ],
   
};
*/

export default {
  mainSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Overview',
    },
    {
      type: 'doc',
      id: 'asset_generation_workflow',
      label: 'Asset Generation Workflow',
    },
    {
      type: 'doc',
      id: 'writing_effective_prompts',
      label: 'Writing Effective Prompts',
    },
    {
      type: 'doc',
      id: 'using_user_interface',
      label: 'Using User Interface',
    },
    {
      type: 'doc',
      id: 'export_integration',
      label: 'Export and Integration',
    },
    {
      type: 'doc',
      id: 'known_issues_limitations',
      label: 'Known Issues and Limitations',
    },
    {
      type: 'doc',
      id: 'examples',
      label: 'Examples',
    },
  ],
};



//export default sidebars;
